sonar.projectKey=nastya-prokopishena_adaptive_planner
sonar.organization=nastya-prokopishena

sonar.projectName=Adaptive Planner
sonar.projectVersion=1.0

sonar.sources=backend
sonar.tests=backend/tests

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=\
backend/tests/**,\
backend/**/__init__.py,\
backend/infrastructure/ml/dataset_builder/**,\
backend/infrastructure/ml/train_*.py,\
backend/infrastructure/ml/export_schedule_load_dataset.py,\
htmlcov/**,\
.venv/**

sonar.test.inclusions=backend/tests/**
sourceEncoding=UTF-8